package cd4017be.rs_ctr.circuit.gates;

import java.util.HashSet;
import java.util.Set;

import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Type;

import cd4017be.rs_ctr.circuit.editor.Code;
import cd4017be.rscpl.compile.Context;
import cd4017be.rscpl.editor.Gate;
import cd4017be.rscpl.graph.Operator;
import cd4017be.rscpl.graph.Pin;

/**
 * Synthetic gates are generated by the compiler and don't exist in the schematic diagram.
 * @author CD4017BE
 */
public class SyntheticOp implements Operator {

	private final Set<Pin> receivers;
	private final Code output;
	private final Operator[] inputs;
	private final Object[] param;

	/**
	 * 
	 * @param output
	 */
	public SyntheticOp(int inputs, Code output, Object... param) {
		this.inputs = new Operator[inputs];
		this.output = output;
		this.param = param;
		this.receivers = new HashSet<>();
	}

	@Override
	public void compile(MethodVisitor mv, Context context) {
		output.compile(mv, context, null, param);
	}

	@Override
	public int inputCount() {
		return inputs.length;
	}

	@Override
	public Operator getInput(int pin) {
		return inputs[pin];
	}

	@Override
	public void setInput(int pin, Operator op) {
		Operator.super.setInput(pin, op);
		inputs[pin] = op;
	}

	@Override
	public Set<Pin> receivers() {
		return receivers;
	}

	@Override
	public Type outType() {
		return output.result;
	}

	@Override
	public Gate<?> getGate() {
		return null;
	}

	@Override
	public int getPin() {
		return 0;
	}

	@Override
	public Operator getActual() {
		return null;
	}

}
